---
- name: add my mappings to Polish keyboard xkb config
  become: yes
  blockinfile:
    path: /usr/share/X11/xkb/symbols/pl
    block: |2
          include "capslock(ctrl_modifier)" // Capslock acts like left Control
          include "shift(both_capslock_cancel)" // both Shifts pressed == CapsLock, press one Shift to cancel
    insertafter: 'xkb_symbols \"basic\" \{'
    marker: "\n// {mark} ANSIBLE MANAGED BLOCK\n"
  notify:
    - reload keyboard layout

- name: swap mouse buttons
  template:
    src: Xmodmap.j2
    dest: "{{ ansible_user_dir }}/.Xmodmap"

- name: create ramdisk
  mount:
    path: /media/ramdisk
    src: ramdisk
    fstype: tmpfs
    opts: nodev,nosuid,noexec,nodiratime,size={{ ramdisk_size }}
    state: mounted
  become: yes

- name: install user-startup service
  template:
    src: user-startup.service.j2
    dest: /etc/systemd/system/user-startup.service
  become: yes
  register: user_startup_installation

- name: propagate service changes
  systemd: daemon_reload=yes
  become: yes
  changed_when: yes
  when: user_startup_installation.changed

- name: enable user-startup
  service:
    name: user-startup
    enabled: true
  become: yes

