---
- name: add my mappings to Polish keyboard xkb config
  become: yes
  blockinfile:
    path: /usr/share/X11/xkb/symbols/pl
    block: |2
          include "capslock(ctrl_modifier)" // Capslock acts like left Control
          include "shift(both_capslock_cancel)" // both Shifts pressed == CapsLock, press one Shift to cancel
    insertafter: 'xkb_symbols \"basic\" \{'
    marker: "\n// {mark} ANSIBLE MANAGED BLOCK\n"
  notify:
    - reload keyboard layout

- name: create ramdisk
  mount:
    path: /media/ramdisk
    src: ramdisk
    fstype: tmpfs
    opts: nodev,nosuid,noexec,nodiratime,size={{ ramdisk_size }}
    state: mounted
  become: yes
