#!/bin/bash
set -o pipefail
set -e
ANSIBLE_LOCATION=~/debian-config

echo "You will be prompted for sudo password twice"
ansible-playbook -K -l local -i $ANSIBLE_LOCATION/inventory $ANSIBLE_LOCATION/bootstrap.yml 

ansible-galaxy install -r $ANSIBLE_LOCATION/requirements.yml --roles-path $ANSIBLE_LOCATION/galaxy_roles
ansible-playbook -K -l local -i $ANSIBLE_LOCATION/inventory $ANSIBLE_LOCATION/playbook.yml 
