- name: install system packages
  package: name={{ item }} state=latest
  with_items:
    - git
    - python3
    - python3-pip

    - vim-gtk # vim with scripting languages and X11 integration
    - tmux
    - htop
    - ranger
    - make
    - curl 
    - net-tools
    - unzip
    - expect
    - jq
    - direnv
    - tree
    - entr
    - whois # mkpasswd ;d
    - xclip

    - network-manager
  become: yes
  tags:
    - pkg

- name: install python packages
  pip:
    name:
      - ptpython # improved Python shell
      - pygments-style-solarized # colorscheme
      - httpie # curl on drugs
      - pirate-get # command line for the pirate bay
      - ansible
      - i3ipc
      - requests
      - dotfiles
    state: latest
    executable: pip3
    extra_args: --user
  tags:
    - pkg

- name: remove crappy system packages
  package: name={{ item }} state=absent
  with_items:
    - nano
  become: yes
  tags:
    - pkg

- include_tasks: system/main.yml

- include_tasks:
    file: nix.yml
    apply:
      tags:
        - nix
  tags:
    - nix
