---
- name: install Docker
  include_role:
    name: geerlingguy.docker
    apply:
      become:
        yes
  vars:
    docker_users:
      - "{{ ansible_env.USER }}"
    docker_package_state: latest
    docker_install_compose: false

