---
- include_tasks: gui.yml

- name: install system packages
  package: name={{ item }} state=latest
  with_items:
    - xorg
    - i3 # Window manager
    - i3blocks
    - fonts-font-awesome # Icons for i3bar
    - xcape # Ctrl => ESC | Ctrl
    - pulseaudio # I know it's technically not related to x ;)
    - conky-all # Fancy stuff on desktop
    - redshift-gtk # Reduce red light

    - imagemagick # contains `convert` package, a dependency of my fancy lock script
    - screenkey # Displays pressed keys, cool for presentations
    - feh # Vim-like picture viewer
    - arandr # GUI for xrandr
    - scrot # Screenshot utility

    - vrms # Virtual Richard M. Stallman <- the best package ever!

    - pavucontrol # Volume control - TODO: Consider dropping in favour of alsamixer
    - alsa-utils # Volume control

    - vlc # media player
    - evince # PDF reader
    - workrave # forces me to take breaks
    - baobab # graphical disk usage explorer

    - graphviz # graph visualization

    - gdb # C / C++ debugger
    - shellcheck # sh linter

    - gcc
    - gcc-multilib # cross-compilation tools
    - g++
    - python3-venv
    - python3-tk
    - python-virtualenv

    - hexcurse # hex editor
  become: yes

- name: install Python packages
  pip:
    name:
      - BlastRadius # Terraform graphs exploration tool
      - pytest
      - click # Python command line framework
    executable: pip3
    state: latest
    extra_args: --user

- include_tasks: browser.yml
  tags:
    - rambox

- include_tasks: dev.yml
